config/routes.rb
Rails.application.routes.draw do
  root 'stories#edit', as: :stories_edit

  patch 'stories/update'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/stories_controller.rb
require "empty_api_response"
require "story"

class StoriesController < ApplicationController
  rescue_from ::StoryDroid::EmptyApiResponse, with: :empty_api_response

  def edit
    session[:story] ||= ::StoryDroid::Story.new.to_s
    @story = session[:story]
  end

  def update
    if pass_recaptcha?
      continued = ::StoryDroid::Story.continued_text(params[:story])
      if continued.length > ::StoryDroid::Story::MAX_LENGTH
        session_cookie_full
        return
      end
      session[:story] = continued
      redirect_to stories_edit_path(anchor: "footer"), status: "303"
    else
      redirect_to stories_edit_path,
        alert: "You failed the reCAPTCHA. Are you a bot? If not, try again!"
    end
  end

  private

  def empty_api_response(error)
    redirect_to stories_edit_path, alert: "#{error} Try again!"
  end

  def session_cookie_full
    redirect_to stories_edit_path,
      alert: "You've reached the story length limit! You can continue your " \
             "story at beta.openai.com/playground."
  end

  def pass_recaptcha?
    NewGoogleRecaptcha.human?(params[:new_recaptcha_token], "continue_story") ||
      Rails.env.test? # recaptcha always fails in test, so skip it.
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="dark">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <%= render 'shared/meta' %>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :recaptcha_js %>
    <link rel="stylesheet" href="https://unpkg.com/papercss@1.8.2/dist/paper.min.css">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <div class="paper container margin-top-large margin-bottom-large">
      <%= render 'shared/flash' %>
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/shared/_flash.html.erb
<% flash.each do |type, message| %>
  <div class="alert alert-primary margin-top-small">
    <%= message %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div id="footer" class="paper container-lg margin-bottom-none">
  <small>
    <a href="https://github.com/fpsvogel/storydroid">GitHub repo</a>. - Made by <a href="https://fpsvogel.com/">Felipe Vogel</a>. -
    Powered by <a href="https://rubyonrails.org/">Ruby on Rails</a>, <a href="https://www.getpapercss.com/">PaperCSS</a>, and <a href="https://openai.com">OpenAI</a>.
  </small>
</div>

app/views/shared/_meta.html.erb
<title>Story Droid</title>
<meta name="description" content="Interactively write a story, or just start it off and see where it goes. Uses OpenAI's new GPT-3 API." />
<link rel="canonical" href="https://storydroid.herokuapp.com/" />

<meta property="og:title" content="Story Droid: Storytelling with AI" />
<meta property="og:description" content="Interactively write a story, or just start it off and see where it goes. Uses OpenAI's new GPT-3 API." />
<meta property="og:url" content="https://storydroid.herokuapp.com/" />
<meta property="og:image" content="https://storydroid.herokuapp.com/android-chrome-512x512.png" />
<meta property="og:type" content="website" />

<meta name="twitter:card" content="summary" />
<meta property="twitter:image" content="https://storydroid.herokuapp.com/android-chrome-512x512.png" />
<meta property="twitter:title" content="Story Droid: Storytelling with AI" />
<meta property="twitter:description" content="Interactively write a story, or just start it off and see where it goes. Uses OpenAI's new GPT-3 API." />
<meta name="twitter:creator" content="@fpsvogel" />

app/views/shared/meta.html.erb
<title>Story Droid</title>
<meta name="description" content="Interactively write a story, or just start it off and see where it goes. Uses OpenAI's new GPT-3 API." />
<link rel="canonical" href="https://storydroid.herokuapp.com/" />

<meta property="og:title" content="Story Droid: Storytelling with AI" />
<meta property="og:description" content="Interactively write a story, or just start it off and see where it goes. Uses OpenAI's new GPT-3 API." />
<meta property="og:url" content="https://storydroid.herokuapp.com/" />
<meta property="og:image" content="https://storydroid.herokuapp.com/android-chrome-512x512.png" />
<meta property="og:type" content="website" />

<meta name="twitter:card" content="summary" />
<meta property="twitter:image" content="https://storydroid.herokuapp.com/android-chrome-512x512.png" />
<meta property="twitter:title" content="Story Droid: Storytelling with AI" />
<meta property="twitter:description" content="Interactively write a story, or just start it off and see where it goes. Uses OpenAI's new GPT-3 API." />
<meta name="twitter:creator" content="@fpsvogel" />

app/views/static_pages/home.html.erb
<h1>Story Droid</h1>

<%= form_with url: stories_create_path do |f| %>
  <%= f.label :story, "Start your story with one sentence or a few:" %>
  <%= f.text_area :story,
                  value: @story,
                  class: "margin-top-small",
                  rows: 6, style: "width:100%" %>

  <%= f.submit "Continue", class: "margin-top" %>
<% end %>

app/views/stories/_story_form.html.erb
<%= content_for :recaptcha_js do %>
  <%= include_recaptcha_js %>
<% end %>

<%# Turbo is disabled (false) so that the 303 redirect in the update action works. %>
<%# see https://github.com/hotwired/turbo/issues/211 %>
<%= form_with url: stories_update_path, method: :patch,
    html: { data: { controller: "story-form", turbo: false } } do |f| %>
  <%= f.label :story, "Start your story with a few sentences:" %>
  <%= f.text_area :story,
                  value: @story,
                  class: "margin-top-small",
                  rows: 6, style: "width:100%",
                  data: { action: 'input->story-form#resizeTextArea',
                          "story-form-target": 'textArea' } %>
  <%= f.submit "Continue", class: "margin-top paper-btn" %>
  <%= recaptcha_action('continue_story') %>
<% end %>

app/views/stories/edit.html.erb
<h1>Story Droid</h1>

<%= render 'stories/story_form' %>

app/views/stories/show.html.erb
<h1>Story Droid</h1>

<%= render 'stories/story_form' %>